### ekf.yaml ###
ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    publish_acceleration: false
    publish_tf: true
    map_frame: map              # Defaults to map
    odom_frame: odom            # The frame created by EKF
    base_link_frame: base_footprint
    world_frame: odom           # EKF localizes odom -> base_footprint

    # ODOMETRY CONFIG (Wheel Encoders)
    # The topic you bridged from Gazebo
    odom0: /odom
    # x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az
    # We use X, Y velocity and Yaw velocity for diff drive
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
    # IMU input disabled to use odom only